# Generated by Django 5.0.1 on 2024-01-17 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=50, verbose_name="baby's name")),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('due_date', models.DateField(verbose_name='predicted due date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['baby_name'],
            },
        ),
        migrations.CreateModel(
            name='diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('WT', 'Wet'), ('DY', 'Dirty'), ('WD', 'Wet and Dirty')], default='WT', max_length=2)),
                ('notes', models.TextField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.baby')),
            ],
        ),
    ]
