# Generated by Django 5.0.1 on 2024-01-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaper',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Sleep start time')),
                ('end_time', models.DateTimeField(verbose_name='Sleep end time')),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.baby')),
            ],
        ),
    ]
