# Generated by Django 5.0.1 on 2024-02-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_diaper_type_feed_medication_medicationentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baby',
            options={'ordering': ['baby_name'], 'permissions': [('can_view', 'Can view baby details')]},
        ),
    ]
