# Generated by Django 5.0.1 on 2024-02-26 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_baby_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaper',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Sleep start time'),
        ),
    ]
