# Generated by Django 5.0.1 on 2024-03-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_diaper_time_alter_sleep_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
