# Generated by Django 5.0.1 on 2024-03-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_baby_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='start_time',
            new_name='time',
        ),
    ]
